; Включает проверку изменения файлов при каждом запросе:
opcache.validate_timestamps=1
; Как часто проверять (0 — проверять каждую секунду):
opcache.revalidate_freq=0
; Настройка xdebug
xdebug.mode=debug,develop
xdebug.start_with_request=yes
xdebug.idekey="PHPSTORM"
xdebug.client_host=host.docker.internal
xdebug.output_dir="/app/var/xdebug"